name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Increase npm timeout
        run: npm config set fetch-timeout 120000

      - name: Use npm mirror
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run

      - name: Run tests
        run: npm run test:ci

      - name: Build
        run: npm run build
