name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Use npm mirror
        run: npm config set registry https://registry.npmjs.org/

      - name: Increase npm timeout
        run: npm config set fetch-timeout 60000

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Lint code
        run: npm run lint -- --loglevel verbose

      - name: Run tests
        run: npm run test:ci -- --loglevel verbose

      - name: Build
        run: npm run build -- --loglevel verbose
